import streamlit as st
import pandas as pd
import plotly.express as px
import os

# Configure the visual layout of the dashboard
st.set_page_config(page_title="Global Banking Stress Monitor", layout="wide", page_icon="🏦")
st.title("🏦 Global Banking Systemic Stress Monitor")
st.markdown("Real-time Macro-Prudential Tracking & Contagion Visualization (Phase 2)")

# 1. Ingest the Data
@st.cache_data
def load_data():
    # Load the new consolidated matrix generated by our pipeline
    matrix_path = os.path.join("data", "processed", "consolidated_systemic_risk_matrix.csv")
    df_master = pd.read_csv(matrix_path)
    return df_master

try:
    df = load_data()
    
    # 2. Top-Level Alert Cards
    st.markdown("### ⚠️ Primary Systemic Threat (By Contagion Hub)")
    
    # Sort by Eigenvector Centrality to find the most critical structural hub
    top_bank = df.sort_values(by="Eigenvector_Systemic_Importance", ascending=False).iloc[0]
    
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Critical Institution", top_bank['Bank'])
    col2.metric("Systemic Hub Score", f"{top_bank['Eigenvector_Systemic_Importance']:.4f}")
    col3.metric("Capital Shortfall (SRISK)", f"${top_bank['SRISK_Shortfall_Billions']:.2f}B")
    col4.metric("Tail Risk (ΔCoVaR)", f"{top_bank['Delta_CoVaR']:.4f}")

    st.divider()

    # 3. Interactive Visualizations
    colA, colB = st.columns(2)
    
    with colA:
        st.subheader("Network Contagion Hubs")
        st.markdown("Eigenvector Centrality (Systemic Importance)")
        fig1 = px.bar(
            df.sort_values("Eigenvector_Systemic_Importance", ascending=True), 
            x="Eigenvector_Systemic_Importance", 
            y="Bank", 
            orientation='h',
            color="Eigenvector_Systemic_Importance", 
            color_continuous_scale="Reds"
        )
        st.plotly_chart(fig1, width='stretch')
        
    with colB:
        st.subheader("Capital Vulnerability")
        st.markdown("SRISK Capital Shortfall under 40% Market Shock (Billions USD)")
        fig2 = px.bar(
            df.sort_values("SRISK_Shortfall_Billions", ascending=True), 
            x="SRISK_Shortfall_Billions", 
            y="Bank", 
            orientation='h',
            color="SRISK_Shortfall_Billions", 
            color_continuous_scale="Oranges"
        )
        st.plotly_chart(fig2, width='stretch')

    # 4. Master Data Matrix
    st.divider()
    st.subheader("Consolidated Macro-Prudential Matrix")
    st.dataframe(df, width='stretch')

except FileNotFoundError:
    st.error("❌ Data matrix missing. Please run `python run_pipeline.py` first to generate the processed data.")